/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description Liveness plus what a question would run as now. The web app calls this on
         *     load, which also starts a serverless instance while the visitor reads.
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Feedback */
        post: operations["feedback_v1_feedback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** History */
        get: operations["history_v1_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/history/{query_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * History Item
         * @description A past result of the caller's, to reopen it. Failed questions have none.
         */
        get: operations["history_item_v1_history__query_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Query */
        post: operations["query_v1_query_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/query/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Query Stream */
        post: operations["query_stream_v1_query_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run user-supplied SQL for a question, through the same checks */
        post: operations["run_sql_v1_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/run/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stream user-supplied SQL through the same checks (from `guardrails` on) */
        post: operations["run_sql_stream_v1_run_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/schema": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Schema */
        get: operations["get_schema_v1_schema_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AgreementPayload */
        AgreementPayload: {
            /** Error */
            error: string | null;
            /** Explanation */
            explanation: string | null;
            /** Outcome */
            outcome: ("agree" | "disagree" | "incomparable") | null;
            /** Ran */
            ran: boolean;
            /** Second Sql */
            second_sql: string | null;
            /** Skipped Reason */
            skipped_reason: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            stage: "agreement";
        };
        /** BacktranslatePayload */
        BacktranslatePayload: {
            /** Alignment */
            alignment: number | null;
            /** Back Translation */
            back_translation: string | null;
            /** Discrepancies */
            discrepancies: string[];
            /** Error */
            error: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            stage: "backtranslate";
        };
        /** Budget */
        Budget: {
            /** Daily Ceiling Usd */
            daily_ceiling_usd: number;
            /** Spent Today Usd */
            spent_today_usd: number;
        };
        /** ClarificationPayload */
        ClarificationPayload: {
            /** Interpretations */
            interpretations: components["schemas"]["Interpretation"][];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            stage: "clarification";
        };
        /** ColumnInfo */
        ColumnInfo: {
            /** Comment */
            comment?: string | null;
            /** Distinct Count */
            distinct_count?: number | null;
            /** Enum Values */
            enum_values?: string[] | null;
            /** Example Values */
            example_values?: string[] | null;
            /** False Count */
            false_count?: number | null;
            /**
             * Is Primary Key
             * @default false
             */
            is_primary_key: boolean;
            /** Max Value */
            max_value?: string | null;
            /** Min Value */
            min_value?: string | null;
            /** Name */
            name: string;
            /** Null Count */
            null_count?: number | null;
            /** Null Fraction */
            null_fraction?: number | null;
            /** Nullable */
            nullable: boolean;
            /** Profile Error */
            profile_error?: string | null;
            /** References */
            references?: string | null;
            /** Sql Type */
            sql_type: string;
            /** True Count */
            true_count?: number | null;
        };
        /** ColumnModel */
        ColumnModel: {
            /** Dtype */
            dtype: string;
            /** Name */
            name: string;
        };
        /** ConfidencePayload */
        ConfidencePayload: {
            /**
             * Band
             * @enum {string}
             */
            band: "high" | "medium" | "low";
            /** Breakdown */
            breakdown: {
                [key: string]: number;
            };
            /** Confidence */
            confidence: number;
            /** Contributions */
            contributions: components["schemas"]["Contribution"][];
            /**
             * Logit
             * @description None when nothing executed (the score is then 0).
             */
            logit: number | null;
            /** Scorer Version */
            scorer_version: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            stage: "confidence";
        };
        /**
         * Contribution
         * @description One term of the confidence logit: weight x value. The terms sum to `logit`.
         */
        Contribution: {
            /** Contribution */
            contribution: number;
            /** Feature */
            feature: string;
            /** Label */
            label: string;
            /** Value */
            value: number;
            /** Weight */
            weight: number;
        };
        /**
         * Detail
         * @description FastAPI's error body: 429, 503, 404 and 422.
         */
        Detail: {
            /** Detail */
            detail: unknown;
        };
        /** ErrorPayload */
        ErrorPayload: {
            /** Error Type */
            error_type: string;
            /**
             * Failed Stage
             * @enum {string}
             */
            failed_stage: "generating" | "clarification" | "guardrails" | "executing" | "sanity" | "backtranslate" | "agreement" | "confidence" | "done" | "error";
            /** Message */
            message: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            stage: "error";
        };
        /**
         * ErrorResponse
         * @description A stage raised. No QueryResult exists; nothing after `failed_stage` ran.
         */
        ErrorResponse: {
            /** Error Type */
            error_type: string;
            /** Failed Stage */
            failed_stage: string;
            /** Message */
            message: string;
            /** Query Id */
            query_id: string;
        };
        /** ExecutingPayload */
        ExecutingPayload: {
            /** Columns */
            columns: components["schemas"]["ColumnModel"][];
            /** Error Class */
            error_class: string | null;
            /** Error Message */
            error_message: string | null;
            /** Estimated Rows */
            estimated_rows: number | null;
            /** Execution Ms */
            execution_ms: number;
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "ok" | "refused" | "failed";
            /** Reason */
            reason: string | null;
            /** Row Count */
            row_count: number;
            /** Sqlstate */
            sqlstate: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            stage: "executing";
            /** Truncated */
            truncated: boolean;
        };
        /** FeedbackRequest */
        FeedbackRequest: {
            /** Correct */
            correct: boolean;
            /** Note */
            note?: string | null;
            /** Query Id */
            query_id: string;
        };
        /** FeedbackResponse */
        FeedbackResponse: {
            /** Correct */
            correct: boolean;
            /** Created At */
            created_at: string;
            /** Note */
            note: string | null;
            /** Query Id */
            query_id: string;
        };
        /** ForeignKeyInfo */
        ForeignKeyInfo: {
            /** From Column */
            from_column: string;
            /** From Table */
            from_table: string;
            /** To Column */
            to_column: string;
            /** To Table */
            to_table: string;
        };
        /** GeneratingPayload */
        GeneratingPayload: {
            /** Assumptions */
            assumptions: string[];
            /** Cost Usd */
            cost_usd: number;
            /** Explanation */
            explanation: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "sql" | "clarification" | "cannot_answer";
            /** Latency Ms */
            latency_ms: number;
            /** Self Confidence */
            self_confidence: number;
            /** Sql */
            sql: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            stage: "generating";
            /** Tables Used */
            tables_used: string[];
        };
        /** GuardrailsPayload */
        GuardrailsPayload: {
            /** Allowed */
            allowed: boolean;
            /** Reason */
            reason: string | null;
            /** Rewritten Sql */
            rewritten_sql: string | null;
            /** Rule */
            rule: string | null;
            /** Sql To Execute */
            sql_to_execute: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            stage: "guardrails";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            budget: components["schemas"]["Budget"];
            /**
             * Fake Llm
             * @description True: a demo-only deployment; answers always come from llm/fake.py.
             */
            fake_llm: boolean;
            /**
             * Mode
             * @description What a new question would run as right now.
             * @enum {string}
             */
            mode: "live" | "demo";
            /**
             * Mode Reason
             * @description Why demo mode; None when live.
             */
            mode_reason: ("demo_deployment" | "switched_off" | "budget" | "call_cap") | null;
            /**
             * Resets In S
             * @description Seconds until the budget and call cap reset (00:00 UTC), when they are the reason for demo mode.
             */
            resets_in_s: number | null;
            /** Scorer Version */
            scorer_version: string;
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        /** HistoryFeedback */
        HistoryFeedback: {
            /** Correct */
            correct: boolean;
            /** Created At */
            created_at: string;
            /** Note */
            note: string | null;
        };
        /** HistoryItem */
        HistoryItem: {
            /** Cached */
            cached: boolean;
            /** Confidence */
            confidence: number | null;
            /** Cost Usd */
            cost_usd: number;
            /** Created At */
            created_at: string;
            feedback: components["schemas"]["HistoryFeedback"] | null;
            /**
             * Mode
             * @default live
             * @enum {string}
             */
            mode: "live" | "demo";
            /**
             * Outcome
             * @description A QueryResult outcome, or 'error'.
             */
            outcome: string;
            /** Query Id */
            query_id: string;
            /** Question */
            question: string;
            /**
             * Sql Source
             * @description model; user or reading for /v1/run.
             */
            sql_source: string;
        };
        /**
         * Interpretation
         * @description One defensible reading of an ambiguous question, with runnable SQL.
         */
        Interpretation: {
            /**
             * Explanation
             * @description What this reading counts, and what it leaves out.
             */
            explanation: string;
            /**
             * Label
             * @description Short slug naming this reading, e.g. gross_revenue.
             */
            label: string;
            /**
             * Sql
             * @description A single PostgreSQL SELECT answering this reading.
             */
            sql: string;
        };
        /** QueryRequest */
        QueryRequest: {
            /** Question */
            question: string;
        };
        /**
         * QueryResult
         * @description Everything a question produced. The `done` payload, and the body of POST /v1/query.
         */
        QueryResult: {
            /** Agreement */
            agreement: ("agree" | "disagree" | "incomparable") | null;
            /** Agreement Explanation */
            agreement_explanation: string | null;
            /** Alignment */
            alignment: number | null;
            /** Assumptions */
            assumptions: string[];
            /** Back Translation */
            back_translation: string | null;
            /**
             * Cached
             * @default false
             */
            cached: boolean;
            /** Cannot Answer Reason */
            cannot_answer_reason: string | null;
            /** Columns */
            columns: string[];
            /** Confidence */
            confidence: number | null;
            /** Confidence Band */
            confidence_band: ("high" | "medium" | "low") | null;
            /** Confidence Breakdown */
            confidence_breakdown: {
                [key: string]: number;
            };
            /** Confidence Logit */
            confidence_logit: number | null;
            /** Contributions */
            contributions: components["schemas"]["Contribution"][];
            /**
             * Cost Usd
             * @default 0
             */
            cost_usd: number;
            /** Discrepancies */
            discrepancies: string[];
            /**
             * Elapsed Ms
             * @default 0
             */
            elapsed_ms: number;
            /**
             * Executed Sql
             * @description What ran: the guardrail may have added a LIMIT.
             */
            executed_sql: string | null;
            /** Execution Error */
            execution_error: string | null;
            /** Execution Ms */
            execution_ms: number | null;
            /** Explanation */
            explanation: string | null;
            /** Guardrail Reason */
            guardrail_reason: string | null;
            /** Guardrail Rule */
            guardrail_rule: string | null;
            /** Interpretations */
            interpretations: components["schemas"]["Interpretation"][];
            /**
             * Mode
             * @description demo: a simulated model answered (llm/fake.py) and nothing was spent.
             * @default live
             * @enum {string}
             */
            mode: "live" | "demo";
            /**
             * Mode Reason
             * @description Why it ran in demo mode; None when live.
             */
            mode_reason: ("demo_deployment" | "switched_off" | "budget" | "call_cap") | null;
            /**
             * N Calls
             * @default 0
             */
            n_calls: number;
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "answered" | "clarification" | "cannot_answer" | "blocked" | "refused" | "failed";
            /** Query Id */
            query_id: string;
            /** Question */
            question: string;
            /**
             * Row Count
             * @default 0
             */
            row_count: number;
            /**
             * Rows
             * @description JSON-safe cells, in column order.
             */
            rows: unknown[][];
            /** Sanity */
            sanity: components["schemas"]["SanityFlagModel"][];
            /** Scorer Version */
            scorer_version: string | null;
            /**
             * Second Sql
             * @description The independently written query agreement compared.
             */
            second_sql: string | null;
            /**
             * Sql
             * @description The SQL the model wrote.
             */
            sql: string | null;
            /**
             * Sql Source
             * @description user: SQL supplied to /v1/run; reading: a clarification's reading, run via /v1/run.
             * @default model
             * @enum {string}
             */
            sql_source: "model" | "user" | "reading";
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            stage: "done";
            /**
             * Truncated
             * @default false
             */
            truncated: boolean;
            /** Validation Errors */
            validation_errors: string[];
        };
        /**
         * RunRequest
         * @description SQL to run for a question: an edited query, or a clarification's chosen reading.
         */
        RunRequest: {
            /** Question */
            question: string;
            /**
             * Source
             * @description reading: the SQL is one of a clarification's readings. Labels only; checks are identical.
             * @default user
             * @enum {string}
             */
            source: "user" | "reading";
            /** Sql */
            sql: string;
        };
        /** SanityFlagModel */
        SanityFlagModel: {
            /** Check */
            check: string;
            /** Column */
            column: string | null;
            /** Explanation */
            explanation: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "fail" | "warn" | "info";
        };
        /** SanityPayload */
        SanityPayload: {
            /** Flags */
            flags: components["schemas"]["SanityFlagModel"][];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            stage: "sanity";
        };
        /** SchemaResponse */
        SchemaResponse: {
            /**
             * Extracted At
             * Format: date-time
             */
            extracted_at: string;
            /**
             * Rendered
             * @description Exactly what the model is shown.
             */
            rendered: string;
            /** Schema Hash */
            schema_hash: string;
            /** Tables */
            tables: components["schemas"]["TableInfo"][];
        };
        /**
         * StageEvent
         * @description One finished stage. On the wire: SSE `event: <stage>`, `data: <this as JSON>`.
         */
        StageEvent: {
            /**
             * Duration Ms
             * @description This stage alone.
             */
            duration_ms: number;
            /**
             * Elapsed Ms
             * @description Since the question started.
             */
            elapsed_ms: number;
            /** Payload */
            payload: components["schemas"]["GeneratingPayload"] | components["schemas"]["ClarificationPayload"] | components["schemas"]["GuardrailsPayload"] | components["schemas"]["ExecutingPayload"] | components["schemas"]["SanityPayload"] | components["schemas"]["BacktranslatePayload"] | components["schemas"]["AgreementPayload"] | components["schemas"]["ConfidencePayload"] | components["schemas"]["QueryResult"] | components["schemas"]["ErrorPayload"];
            /**
             * Stage
             * @enum {string}
             */
            readonly stage: "generating" | "clarification" | "guardrails" | "executing" | "sanity" | "backtranslate" | "agreement" | "confidence" | "done" | "error";
        };
        /** TableInfo */
        TableInfo: {
            /** Columns */
            columns?: components["schemas"]["ColumnInfo"][];
            /** Comment */
            comment?: string | null;
            /** Foreign Keys */
            foreign_keys?: components["schemas"]["ForeignKeyInfo"][];
            /** Name */
            name: string;
            /** Referenced By */
            referenced_by?: components["schemas"]["ForeignKeyInfo"][];
            /**
             * Row Count
             * @default 0
             */
            row_count: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    feedback_v1_feedback_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Detail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    history_v1_history_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    history_item_v1_history__query_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                query_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryResult"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Detail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    query_v1_query_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Detail"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    query_stream_v1_query_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryRequest"];
            };
        };
        responses: {
            /** @description text/event-stream. Each event's data is a StageEvent; the last is `done` (payload: QueryResult) or `error` (payload: ErrorPayload). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StageEvent"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Detail"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Detail"];
                };
            };
        };
    };
    run_sql_v1_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Detail"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    run_sql_stream_v1_run_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunRequest"];
            };
        };
        responses: {
            /** @description text/event-stream. Each event's data is a StageEvent; the last is `done` (payload: QueryResult) or `error` (payload: ErrorPayload). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StageEvent"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Detail"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Detail"];
                };
            };
        };
    };
    get_schema_v1_schema_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchemaResponse"];
                };
            };
        };
    };
}
